name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      env:
        token: ${{ secrets.DO_API_KEY }}
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Build and push the Docker image to DO
      run: | 
        docker build . --file Dockerfile --tag registry.digitalocean.com/webpersonal-server/image:latest
        docker push registry.digitalocean.com/webpersonal-server/image:latest
